/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `bs_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `bs_db`;

CREATE TABLE IF NOT EXISTS `Artists` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` char(100) NOT NULL DEFAULT '',
  `Alias` char(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `Tracks` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` char(150) NOT NULL DEFAULT '',
  `Date_Added` datetime DEFAULT NULL,
  `by_Artist1` int(11) DEFAULT 0,
  `by_Artist2` int(11) DEFAULT 0,
  `by_Artist3` int(11) DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `FK_Tracks_Artists` (`by_Artist1`),
  KEY `FK_Tracks_Artists_2` (`by_Artist2`),
  KEY `FK_Tracks_Artists_3` (`by_Artist3`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
